<div class="view">

    <h3>Pagamento com Boleto Bancário</h3>

    <?php if (isset($this->error) && $this->error != ""): ?>
        <div class="error">
            <span><?php echo $this->error; ?></span>
        </div><br />
    <?php endif; ?>

    <b>Valor da Compra: </b><?php echo Helpers_Session::getInstance()->getSessVar('preco_produto') + Helpers_Session::getInstance()->getSessVar('preco_frete'); ?><br/><br/>

    <h3>Parabéns! Seu pedido foi confirmado. Assim que recebermos a confirmação do pagamento, enviaremos o(s) produto(s).</h3>
    
    *O boleto será enviado para o seu e-mail.

</div>