<div class="view">

    <h3>Pagamento com Boleto Bancário</h3>

    <?php if (isset($this->error) && $this->error != ""): ?>
        <div class="error">
            <span><?php echo $this->error; ?></span>
        </div><br />
    <?php endif; ?>

    <?php 
        $frete = Helpers_Session::getInstance()->getSessVar('preco_frete');
        $preco = Helpers_Session::getInstance()->getSessVar('preco_produto');
    ?>
    <b>Valor da Compra: </b><?php echo $preco + $frete; ?><br/><br/>

    <h3>Parabéns! Seu pedido foi confirmado. Assim que recebermos a confirmação do pagamento, enviaremos o(s) produto(s).</h3>
    
    <p>ID da transação: <?php echo $this->pagto->PagarViaBoletoBancarioResult; ?></p>
    <p>Use esse número para confirmar seu pagamento.</p>

    
    <p>*O boleto será enviado para o seu e-mail.</p>

</div>
