<div class="view">

    <h3>Pagamento com Boleto Bancário</h3>

    <?php if (isset($this->error) && $this->error != ""): ?>
        <div class="error">
            <span><?php echo $this->error; ?></span>
        </div><br />
    <?php endif; ?>

    <b>Valor da Compra: </b><?php echo Helpers_Session::getInstance()->getSessVar('preco_produto') + Helpers_Session::getInstance()->getSessVar('preco_frete'); ?><br/><br/>

    <div class="form">
        <form action="" method="POST">
            <label>Agência</label><br/>
            <input type="text" name="agencia" id="agencia"><br/>
            <label>Conta</label><br/>
            <input type="text" name="conta" id="conta"><br/>
            <br/>
            <div id="buttons">
                <input class="large awesome orange" type="submit" value="Finalizar" />
            </div><br/>
        </form>
    </div>
    
    *O boleto será enviado para o seu e-mail.

</div>