<div class="view">
	<h3>Endereço de Entrega</h3>

    <?php if (isset($this->error) && $this->error != ""): ?>
        <div class="error">
            <span><?php echo $this->error; ?></span>
        </div><br />
    <?php endif; ?>

	<?php if (!isset($this->endereco)): ?>
    <div class="form">
        <form action="" method="POST" id="login_form">
            <label>CEP</label><br/>
            <input type="text" name="cep" id="cep" value="<?php echo $this->cliente->return->CEP; ?>"><br/><br/>
            <label>Número</label><br/>
            <input type="text" name="numero" id="numero" value="<?php echo $this->cliente->return->numeroEndereco;?>"><br/><br/>
            <label>Complemento</label><br/>
            <input type="text" name="complemento" id="complemento" value="<?php echo $this->cliente->return->complementoEndereco;?>"><br/><br/>
            <div id="buttons">
                <input class="large awesome orange" type="submit" value="Pesquisar" />
            </div><br/>
        </form>
	</div>
	
	<div class="info">
		<?php else: ?>
		<table class="info">
		<?php foreach($this->endereco as $field => $value) {
		    echo "<tr><td>$field: </td><td>$value</td></td>";
		} ?>
		</table>
		<br/>
		<div id="buttons">
        <?php $id = Helpers_Session::getInstance()->getSessVar('produto_id'); ?>
		<a style="margin-right: 10px;" 
                    href ="<?php echo $this->baseUrl(); ?>/Compra/endereco/id/<?php echo $id; ?>" 
                    class="large awesome orange" 
                    id="voltar" />
           Voltar
        </a>
		<a style="margin-left: 10px;" href ="<?php echo $this->baseUrl(); ?>/Compra/pagamento/" class="large awesome orange" id="prosseguir" />Prosseguir</a>
		</div>
		<br/><br/>
		<?php endif; ?>
    </div>
</div>
