<?php if (!isset($this->endereco)): ?>
<div class="view">

    <h3>Endereço de Entrega</h3>

    <?php if (isset($this->error) && $this->error != ""): ?>
        <div class="error">
            <span><?php echo $this->error; ?></span>
        </div><br />
    <?php endif; ?>

    <div class="form">
        <form action="" method="POST">
            <label>CEP</label><br/>
            <input type="text" name="cep" id="cep" value="58407-035"><br/>
            <label>Número</label><br/>
            <input type="text" name="numero" id="numero"><br/><br/>
            <div id="buttons">
                <input class="large awesome orange" type="submit" value="Pesquisar" />
            </div><br/>
        </form>
    </div>
</div>
<?php else: ?>
<table>
<?php foreach($this->endereco as $field => $value) {
    echo "<tr><td>$field</td><td>$value</td></td>";
} ?>

</table>
<a href ="<?php echo $this->baseUrl(); ?>/Compra/pagamento/id/<?php echo $this->detalhes[0]; ?>" class="large awesome orange" id="voltar" />Voltar</a>
<a href ="<?php echo $this->baseUrl(); ?>/Compra/pagamento/" class="large awesome orange" id="prosseguir" />Prosseguir</a>
<?php endif; ?>