<div class="view">
	<h3>Método de Pagamento</h3>
<table class="info">
    <tr>
        <?php
            $preco = Helpers_Session::getInstance()->getSessVar('preco_produto');
            $frete = Helpers_Session::getInstance()->getSessVar('preco_frete');
        ?>
        <td>Preço do Produto: </td>
        <td><?php echo floatval($preco); ?></td>
    </tr>
    <tr>
        <td>Frete: </td>
        <td><?php echo floatval($frete); ?></td>
    </tr>
    <tr>
        <td>Total: </td>
        <td><?php echo floatval($preco + $frete); ?></td>
    </tr>
</table>
<br/>

<div class="form">
<form action="" method="POST" id="login_form">
	<label>Método de Pagamento</label><br/>
    <select id="forma_de_pagamento" name="forma_de_pagamento">
        <option value="banco">Banco</option>
        <?php if ($this->situacao_cpf == 'regular'): ?>
            <option value="cc">Cartão de Crédito</option>
        <?php endif; ?>
    </select>
	<br/>
	<br/>
    <div id="buttons">
        <input class="large awesome orange" type="submit" value="Selecionar" />
    </div>
	<br/><br/>
</form>
</div>
</div>
