<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>StOA</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/main.css')
                ->appendStylesheet($this->baseUrl() . '/css/menu.css');
        ?>
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/main.js') ?>
    </head>
    <body>
        <div id='banner'>
            <div id='login'>
                <?php 
                    if($this->authenticated){
                        $ref = $this->baseUrl() . '/login/logout';
                        echo("<a id='logo' href='".$ref."'>Logout</a>");
                    }
                    else{
                        $ref = $this->baseUrl() . '/login/index';
                        echo("<a id='logo' href='".$ref."'>Login</a>");
                    }
                ?>
            </div>
            <div id='logo'>
                <img id='logo' alt="StOA"
                     src="<?php echo $this->baseUrl(); ?>/img/logo.png">
            </div>
            <div id='main_menu'><?php echo $this->partial('partials/menu.phtml'); ?></div>
        </div>
        <div id='side_menu'></div>
        <div id='content'>
<?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>
