<div class="view">

    <h3>Login de Clientes</h3>

    <?php if (isset($this->error) && $this->error != ""): ?>
        <div class="error">
            <span><?php echo $this->error; ?></span>
        </div><br />
    <?php endif; ?>

    <div class="form">
        <form id="login_form" action="" method="POST">
            <label>CPF</label><br/>
            <input type="text" name="cpf" id="cpf" size="15" /><br /><br />
            <label>Senha</label><br/>
            <input type="text" name="senha" id="senha" size="15" /><br />
            <br />
            <div id="buttons">
                <input class="large awesome orange" type="submit" value="Entrar" />
            </div>
            <br/>
        </form>
    </div>
</div>